const chapters=[
{title:"Episode 1: Ballin’ to Crawlin’",kicker:"Roots • Family • The Game • Prayer",text:`This is a story about a young man who grew up without his father. To him, his family were all the boys in the hood, but he had a grandmother. Grandmothers are very special, blessed, full of wisdom. They may say something to you—you don’t quite get it, but it doesn’t go away. And as you get older, you’ll look back one day and say, Oh, that’s what she was talking about. Those are planting seeds, because the Bible says: Bring up a child in the way he should go, and when he is old, he will not depart…

It’s like having grandma’s hands. You have an understanding of morality, and you have a standard that she set. So you know, we’re just that way, and the world is what it is.

To him, his family were the boys in the hood, and he joined the gangs. He moved up the ranks as a young soldier and started selling drugs. He went from resale to wholesale. And now he’s ballin’. He’s still grandma’s hands.

He found a young lady, they fell in love, got married, and had two kids. One day at an outing, he looked over his family and said, I don’t want them to go through what I went through. So he tried everything he could to get the game out of his system.

To him, the game was the environment that came with whatever you do. It’s more addictive than the thing itself. If you’re sitting at home with your stash, you can let your guard down. But in the environment where you hustle, you have to stay alert. Gangs and enemies come at you. That’s the game.

And when the weight of it all pressed heavy on him, he turned to God. His voice broke through the noise of the streets, and this was his cry:

I grew up fast as a child.
I wasn’t too bad, sometimes a little wild. Do you feel me?
Then I got sad, because I missed my dad.
I needed him in my life to fulfill me.
But then I found the game that thrilled me.
Now I want out—I know what it’s about.
My babies need their dad to heal me.
I went from ballin’ to crawlin’ on my knees,
Asking, Lord, please help me get this game out of my system.`},
{title:"Episode 2: Preacher in the Game",kicker:"Transformation • Ministry • Fall • Spiritual Warrior",text:`This is a story about a young man who grew up without his father. To him, his family were all the boys in the hood, but he had a grandmother. Grandmothers are very special, blessed, full of wisdom, and they may say something to you. You don't quite get it, but it doesn’t go away. And as you get older, you'll look back one day and say, oh, that's what she was talking about. Those are planting seeds, because the Bible says to bring up a child in the way he should go, and when he is old, he will not depart from it—like having grandma's hands. You have an understanding of morality, and you have a standard that she set. So, you know, we're just that way, and the world is what it is.

To him, his family were the boys in the hood, and he joined the gangs. He moved up the ranks as a young soldier, and he started selling drugs. He went from resale to wholesale, so now he's balling. He's making his money. He's still grandma's hands. And he finds a young lady out there, and they fall in love and get married, and he has two kids. One day they're at an outing, and he's looking over his family. He said, I don't want them to go through what I went through. So he tries everything he can to get the game out of his system.

To him, the game is the environment that comes with whatever you do. It's more addictive than what you do, and it causes the game for the sake of a point of view. Because if you're sitting at home with your stash, you can have your guard down. But if you go out in that environment where you do it and get it, you have to have your guard up, because there's a whole bunch of little gangs coming at you to try to get your stuff. And if you're broke, you can pass through that environment. You know enough games to get your money and go home. For the sake of a point of view, that environment is called a game. And he was looking back, and he's like, OK. And he tried, and he asked God.

A little song goes like this:

I grew up fast as a child.
I wasn't too bad. Sometimes I was a little wild. Do you feel me?
And then I got sad because I missed my dad.
I needed him in my life to fulfill me.
But now I got a job from being all alone.
Found something in this game that would thrill me.
But now I want out. I know what it's about.
My babies need their dad for a killing.
I went from falling to crawling on my knees.
Asking, Lord, please help me get this game out of my system.
This is my son. To me, he's number one. But I got to hide my gun. Do you feel me?
My little girl. Daddy's sweet pearl. Tell me the whole world that she needs me.
And this is my wife. God has been nice. Give her a little respite. And she loves me.
Went from falling to crawling on my knees. Asking, Lord, please help me get this game out of my system.

That relationship he established by the touch of God. He went and bought two belts and pulled his pants up. And got some suspenders. Held them all the way up. Made sure he didn’t go back down to where he came from. And he started in the ministry. He got to know God. The kids went to school. Got the ABCs, PhDs. Got businesses. The church was flourishing.

Let me tell you something. Whenever you have an obstacle in your life, however simple it may seem, once God removes it—or you put yourself in the position to have it removed—then you go on to another level. It's not over. Because the devil is sitting on another level too, ready to keep you from knowing who you are. Yeah. You might find out what you have access to. Uh-huh. And learn he belongs under your feet, by the most powerful name: Jesus Christ.

And he believed that. He's out there and he's refraining from sin and all this. And all of a sudden, they get a divorce. And he goes and sits on what the old people called the seat of do-nothing. He didn’t do anything. He sat there, not moving. I don’t know. And then he starts smoking cigarettes. And then he starts smoking weed. And looking at the women and touching the women. And he realized, wait a minute. A part of me likes this. But I can't commit to it. Because I know about the reality of Jesus Christ. Oh, my goodness. Now, he's in that dilemma. And the thing he wanted to do, he can't do.

Anyway, everybody will have themselves there, whatever they want to celebrate. And guess what? He won’t stop talking about Jesus. Because it's like fire shut up in his bones. And God just won't let him go. You understand? And, man, let me tell you something. He's something else.

When you see him in the day, he's like this:

Strolling with my gators, I'm creating haze.
And with my stingy grin, they say, oh, mama, look at him.
He's an imp, a wimp, a wannabe pimp.
He can't be a buster, so he's got to be a hustler.
Because I can see the glitter in his eyes.
I want to tell you something you can't deny.
I want to give you hope without giving you gold.
And if you listen, I'm going to tell you how.
Because he's a preacher. Preacher in the game.
Walking hard against the flow. Sets his curious goal.
A platinum star. Jesus Christ, my son.
I'm here to win. I'll place the show.
I'll be the preacher. Preacher in the game.
Me and my Jesus soul. I won't give the devil no more control.
Because if he won't fight, I’ll get on my knees at night.
And stand back and watch the Holy Ghost deliver the preacher.

Oh, yeah. That was his story. And that's who he was. And you see him all around every now and then. You got a little bit of me too, you know. A preacher. Just because you're in the game doesn't mean God forgot you. You know what he told me? He said, you forgot I loved you. Then I thought about it. He said, remember, I died for your sins. One time he told me, he said, this is something. What are you hiding for? You already know that I'm everywhere, see everything. What are you hiding for? He said, do you think whatever you're doing is going to water down what I've already done for you? And that made me think.

So he's talking about a destiny. Oh, he said, before the foundation—wait a minute, I start to pay attention. Oh, so it doesn’t hurt to look a little deeper. Because it's pulling on you like the truth does, you understand. And it gets sweeter the closer you get. Because you can tell the peace is on its way. You finally know what to do. And God told him straight up, but now we have to find out how you are going to do it.

Every man’s got that dilemma. It's nothing new, it's normal. But they don't know how to look at it. So the little boy that grew up to be a man now, he ended up being a spiritual warrior. Because, you know, he's been talking to God. Listen, when they tried to tell him that's not God, but the devil, he said God told him, do you call yourself son? Huh. Because he's a liar, you understand. So I'm going to let you go, because the little boy doesn't want me to take the show. But I love him too. The preacher in the game.

They're all around him.

All right. I went off, man. I started getting off. Anyway. See y’all.`},
{title:"Episode 3: The Big Picture",kicker:"Loss • Somewhere • The Parallel World • Destiny",text:`Hello, this is RLNG, the preacher in the game. We're from ballin' to crawlin', and this is episode three, the big picture. It's been about eight months now since I lost everything. I went through a storm, a mental storm that just swept me off my feet, in my head, you know what I mean? And I'm recovering better now. The things that happened was a big punch to my life. But I sit back now in retrospect and look back to where I am and how I got here. Yes, I'm still in the game, because at the time I lost everything, that's all the people I knew was in the game. And the game is where I got caught up. Right now, my mission is to make it out with something other than just my life and the hope that God gives. If I don't, the life and the hope is just fine. Trying to get back online. You see, I learned a lot, and this is some of my experiences going through the game. And I define the game as a place where you do what you do and buy what you buy. It's contrary to law, if you will. And we call that the game. And that's where this is coming from.

I'm here now, and I got a nice little place, and I'm sitting around. I got a couple nice looking ladies down the street, but I'm in it and trying to get out of it. I start doing like I used to do, because I wasn't going nowhere. And here I am, still here, on my way out. If I got to go from bawling to crawling all over again, I got to make it out.

I'm in a place called somewhere, and the people there don't like to breathe there. Some of them don't even know how they got there. I know how I got there, and that's what I want to share with you. You've probably been there, too, but just didn't have it organized to figure out where you was. See, I was here, but I wasn't there. I seen you walking, seen you talking, but I was here, but I wasn't there. I was in a place called somewhere. I've been going back and forth for almost 40 years. It almost became a way of life to add with the other life that I had, but it don't work, because I can be straight and go through somewhere, and I'll soon be in an altered state of mind. It just don't work trying to walk both ways. It's confusing that you never get nothing done.

People talking to you that you can't see in a place called somewhere, but I was here, but I wasn't there. I seen you walking, I seen you talking, but I wasn't there. I was here, but I wasn't there. I go to work and wash my car, I was here, but I wasn't there. Any opportunity I got to go there, I'm going somewhere. No matter what I have, it's like a parallel world. It's like just like this one, but it's not there. You can exercise almost anything you think about. You can see more of it than you would normally at a place called somewhere. The people are like they are here, but they're not there. They're a little different, and the way they think is more freer, and it'll get on you, and you get stuck that way. And the whole thing about it, it's so more normal, it's abnormal, or it can be abnormal, it seems normal, but you never know you're stuck until you try to get out.

I'm trying to make it through one more time and go back to my destiny, which lays there waiting for me to take my seat, but I got to get there. I got to lay aside everything that does so hinder me, and the things that got me in here, they're very prevalent. They're surrounded by them, surrounded by them, and people. I got to get away. I read a book one time about 12 steps or something that you have to change people, places, and things. Well, you ain't got nothing, and you got stuck in the middle of the other thing, man. You really got to put in some work. You got to have a relationship with something bigger than you, because every time I count on me, I by myself mess me up, and in this place called somewhere, let me tell you something, it's three of me. It's me, myself, and I, and they have come to life, and I've had a hard time trying to make it back, but I'm determined to make it, because I got promises I'm holding on to. You hold on to promises, too, promises that'll help you through.

You know, I didn't know anything about the promise giver until my grandmother said something one day, and she told me, oh, God, and I said, what is God? I was very young, and she kept saying it, and all the things God blessed me and God did, I'm looking for God. Christmas time, I'm not looking for Santa Claus. I'm looking for God. Do he come down the chimney, I asked her. She said, he's always with you. Never leave you, nor forsake you, and I, you know, I'm okay, so I went on about that, but I was very lonely at the time, because I didn't know my father, you know, but all my siblings, they knew, and one time, I never got treated bad, but one time, we were just having a good time, and I ran up to the corner, and I stopped, and I looked, and I seen everybody happy, and I said to myself, I wish I had my daddy, and a voice that rang inside of my head and all over my body. Sorry to interrupt. I'm sorry to interrupt. That's all right. Is it okay, with your permission, if I go ask Kiki if she's all right, or if she needs my tent, and if, is it all right? She actually wants me to ask her if she's all right.`},
{title:"Episode 4: High and Low — The Big Picture About Steps",kicker:"Steps • Maintenance • Trust • Human Nature",text:`I've been up high and I've been down low. I've even been in the middle. I really have. Living in the middle is so unsatisfying because my mind wasn't made up which way I wanted to go. But I found out one thing and I know it for myself. This is the big picture about steps. When I had an opportunity to do everything I wanted to do, I took the necessary steps to get it done. And I did. I tell people all the time that, you know, you take the necessary steps and do what you got to do. But you can get there. But the key to winning is maintaining your state there. Don't drop down to where it's even because there's no joy in it. There's no commitment behind it. You just exist. You can't just exist after you run across your God. You got to do something.

And when I didn't do or waited too long, I looked back and the problem was I didn't take the necessary steps to maintain what I had gotten. I was blessed with what I got, but I never made it over the top because I didn't take the necessary steps. When there's a plan set for you and your destiny is waiting for you to get back in your seat and ride, you have to take the necessary steps to get back in your seat. That means get up and go to your seat.

But now I'm recovering from the losses. My heart's no longer broken. It still hurts. People you've been around, the people you let down, the people you hide from, because you didn't take the necessary steps. I prayed about it and I found out there's steps I got to take to get out of this rut, this state of mind, this fake depression, this thing that overcomes us every time we examine ourselves and see a bunch of holes from self-inflicted wounds. You take the steps to get out of the way next time, won't you?

Well, as I continued on my journey to escape from being bound in my mind, in my heart, and the only thing I had left was my faith in the book written by God. Has he used me? And I found out for myself that they were designed for what I'm going through. They're designed for what you're going through. I found out he was a complete God because he covered everything. If he laid your destiny before the foundation of time, he knows what you're gonna go through. That's the grandeur of this God we're talking about. Oh, you gotta really learn to love him by listening, talking to him. I know you can't see him, but take a step forward and stand up and understand faith, and faith comes by hearing, and hearing comes by the Word of God.

And so, you know, once I got a hold of that and desperation made me grab a hold with both hands, I tell you what I found out for myself. It's real, and every instruction that is written, since he said there's nothing new under the sun, is written on your behalf. Now, this may be too big for your mind to realize that you have a God you can't see, that has prepared everything for what he wants you to do. That's awesome. When you can grab that, you'll see a love that you can't give. You'll see a love that looks down on your faults and sees your needs. You won't understand why because you feel so guilty about taking the wrong steps, but it's the kind of love that does that. It's the kind of love that has parts to it that embrace you, won't let you go. I'll tell you, it's a wonderful thing to know for yourself.

As I journeyed to get out to a better state of mind and get out of the environment I was in, which is what kept me in there so long, which was my biggest downfall, because I read a book one time about some 12 steps that said you have to change people, places, and time, and people, places, and everything. You got to change everything. And so, you know, I did that and I found myself alone. It wasn't no good for me anyway. I wasn't happy about it. I had no benefit to it. I was losing more than what I was gaining. All I gained was folly, folly, folly, folly. I realized I had too much to lose with just a moment's pleasure here and there, and found myself all alone.

But I wasn't all alone, because I picked up the book again, and I saw things in there that touched my heart. And I said, how can these words touch my heart like they do? I felt something on the inside, on the outside, in my mind, in my heart that was changing. And I asked, can you just change me and give me a better spirit, a better state of mind? And in a few days, I saw for myself things I wanted to let go of, I no longer had a desire for. I said, wow. I took the steps to trust, and the key word is trust, and patience, and love.

I heard a voice one morning from him, my beloved. He said, trust me. And I'm like, okay. Took me a minute to learn how to trust what I couldn't see. But I got back into the book and read some more words, and I said, these words are something else. And the voice spoke to me, and he said, I am alive, and everything I give you is alive. That's why it cuts so much. And I began to study that phrase, and I realized it's a whole different mindset, because it was spiritual.

Ah, I wanted to find out how I was made, and how this thing works. And I get a big picture of what the big God told me. I jumped into the book, beginning at Genesis, and it was just God, God, God, God did this. God saw that. God spoke that into existence. And he gets down to a verse where he says, let us make man in our image and likeness. And I, us, wait a minute, because I'm really trying to get this thing now. If it was only you in the beginning, who were you talking to? And a scripture came to mind, Ephesians 1, 11 says that God created all things by the counsel of his own will. I said, so you were talking to yourself. And the very essence of God is what he wants to do. People call him to do his will, to do his will. It's something about love in this thing now.

And I begin to understand, I don't have the time to tell it all, but I give you a big picture of it. And then, I'm still wondering about, who was he talking to? And he was talking to himself. It was just him. And so, this is now where he formed man. And he formed man from the dust of the earth. Now, if he's gonna make us in his image and likeness, he's not a man. He's a spirit. So, he formed man from the dust of the earth. He breathed into his nostrils the breath of life. And man became a living soul. So, to break it down, you have now a brain, flesh, a body, and a spirit. When he breathed into his nostrils, he deposited his image and likeness in his spirit, and that's what we're made of. We're housed in what's called human nature.

And I found out for myself, human nature and spirituality are contrary one to the other. Oh, man, they cause a problem. So, you can't do what you want to do, because human nature is pulling on you. What do I mean? God speaks to us through our spirit, to the mind that it may react. I'll put it in layman's terms. And the biggest thing that our position is, lust of the flesh. There's three categories, lust of the eye, lust of the flesh, and the pride of life. Now, if you make those categories, and every time you have a problem, you don't understand, something's coming up, or something's leading that way, categorize it, and you'll address it. When you address it, then you can solve it. You don't have to wake up tomorrow with something you had on your mind today. You want to wake up tomorrow with a clean mind, to thank God for the information, to thank God for the mercies you can see now, to thank God he'll show you all kind of things, which he, which is, what he's doing is none of`},
{title:"Episode 5: The Big Picture — Steps Through the Cross Roads I Know for Myself",kicker:"Wisdom • Understanding • Obedience • Love",text:`Well, I'm still walking. I'm still stepping. I can see a little light ahead, but I don't see the end of the tunnel. But I can see the light, and I know that there is a way out of despair of what I didn't want to be, what I wasn't made to be. But the love that I'm walking in, while I'm walking steps through my crossroads, I've got to win every step. I've got to cross every trial, tribulation, especially the ones I've been in. It's not as easy as it sounds because it'll grab you. It'll grab a part of your flesh, and it wars against the spirit. So you can't make up your mind. You're always saying, the things I want to do, I don't do. The things I don't want to do, I do. But Paul said, the things I don't want to do, if I do them, it's not me. It's the sin in my flesh. And I said, well, Lord, how do we overcome that? And the question came to me, how do you fight a fixed fight? Bob and weave? No. And the answer rose up. It says, surrender and win. If the fight is fixed, surrender and win. Your destiny is fixed and set and waiting for you to get back in the sea and realize everything you have access to by positioning yourself to access it. You may have to lay aside every sin and wait because that's so easy to distract you. That's what the book says.

You know, I came across another scripture as I was stepping. And it says, he who lacks wisdom as God who gives it liberally. I went to work. God, give me wisdom. Give me wisdom. I can make these steps or give me what is hard out there trying to make these steps. And I couldn't say by myself because I'm still talking to him. Oh, my goodness. And I'm going to ask for wisdom. Lord, give me wisdom, wisdom, wisdom. Lord, give me wisdom. And he spoke to me again and he said, son, you are asking me for something you don't know anything about. How would you know when you got it?

And I thought about it and wisdom must have hit me that quick. But I know it didn't. But but my desire to know. And I started reading. That's what I think about wisdom. When I hear that first, looking way back, Sunday school, Solomon, we think of Solomon, you think of wisdom. And I said, OK, and I started reading Proverbs and no one knew Proverbs was about wisdom. And it said, I'll summarize what I got out of what was good for me. It said. He who finds wisdom finds a good thing. Yeah, I'm comfortable now with wisdom comes riches and honor and blessings. OK, that's good. That's good. And it said to embrace her, have the nearest kin. I said, wait a minute.

Took me back to when I was trying to find out how it was made. And embrace her. And then I thought about it. Go back to Sunday school. You see, if you put words inside, I call it word installation. And when he told his disciples to go out, they don't need a script. What you got inside them will come up at the right time. And it came up.

And I know that for myself. I'll tell you God is so awesome and he's so loving. If you know about him, you can't help but love. People, I love you, I forgive you because of the love of God. Surpassing all understanding. The love of God is so wonderful. It'll keep you, it'll keep you from falling. And I remember the scripture says, the steps of a good man are ordered by the Lord. And though he fall, he shall not be utterly cast down. For the Lord will uphold him. That's love.

See, the big picture is this. You got to take steps to get to God. You can cry out and love will catch you, but you got to take steps to learn to be obedient to God. If you think about it, the first sin was disobedience. So in order to be straight, you got to have some obedience. Obedience to what? Obedience to the words that he left for our instructions.`},
{title:"Episode 6: Thank You Story",kicker:"Gratitude • Praise • Deliverance • Solid Ground",text:`You know, I really think that as much as I know that God has been good to me, brought me through, he's got things that he uses to bring us through, and we can see high enough where the trail goes, how to stay on track. Fall back in love with things like mercy and peace and grace, you know, things that make you fall in love with this God you can't see, but you know he exists because he's relentless in his pursuit to manifest himself to his greatest creation. And, you know, when I think about that, I feel special. If I'm dissuaded or distracted, my special feeling leaves, so I had to learn how to keep it and not be so distracted that I feel hopeless. When I felt that way, I couldn't change something. I was lost in the world of sin. I was separated from my God. Didn't have no peace within, but it's something about his love, you know, alienating in my mind from the commandments of the Lord. I tried to fill the void with things I couldn't afford, but empty, so empty, when the life I started to live, I thought about it, God gave his only son, and all he ever did was give, and I thank him for lifting me up, and I thank the Lord for taking away that cup. I thank him for turning me around, and I thank the Lord for setting my feet on solid ground, but I gotta tell you something now, it's not the way I wanted to glorify his name, but since I found the Lord, my life ain't been the same.

When you wake up in the morning, recognize what you already know, the reality of the existence of your God. Recognize it, learn to talk to him a little bit, add him to your daily program, the wealth and woes that you have that seem to come out of nowhere, they fall off when you feed yourself the word of God, the bread of life, and be not conformed, but be you transformed by the renewing of your word, of your mind, rather, in the word of God. Thank you for lifting me up, Lord. Thank you for taking away that cup. Thank you for turning me around, and thank the Lord for setting my feet on the solid ground. Amen.

You know, when I got into this little church, they had a lingo they spoke, you know, called it shoutin'. They said, you gonna shout. I ain't finna scream, I ain't finna, I ain't, I don't talk loud. No, no, you gonna shout, though. No, no, no, no. The word is coming, and you shout, shout. I don't know what you're talking about. I'm cool. And the preacher got up, and all they said was, hallelujah, and something came across the whole audience. It was like a wave of air that was soothing and comforting and had an anointing to it, and tears began to fall from my eyes, and I looked around, and my David was crying, too, and I know a man ain't supposed to cry, but it felt so good. I just didn't know what to do. That's when I realized about the goodness of Jesus, and all he's done for me. Let me tell you something. My soul cries out. I gotta praise him, because he cleansed my heart from things I didn't see, and they hindered me from praising him, and kept me sober down in sin. I think about the sacrifice I've been bought with the price of life.`},
{title:"Second Story",kicker:"Praise • Joy • Strength",text:`I praise him. I've got to praise him. Burying aside every sin and burying aside every weight, I praise him. When all mankind seemed lost, his blood became the cause, and I praise him. Just let me praise him. I've got to praise him. And I found it when I praised him, and I connected, hooked up, that state of mind. I felt so joyful and so strong when I realized the words God said, the joy of the Lord. I'm trying to be happy in Jesus and be as strong as I can be, and be strong enough to fight back the things I didn't believe. Thank you. I've got to praise him. As a matter of fact, I thank God for that praise. We're going to get to that in a little bit. Thank you, Lord.`}
];

const select=document.getElementById('chapterSelect');const readerTitle=document.getElementById('readerTitle');const readerKicker=document.getElementById('readerKicker');const readerText=document.getElementById('readerText');const voiceSelect=document.getElementById('voiceSelect');const rate=document.getElementById('rate');const rateLabel=document.getElementById('rateLabel');const status=document.getElementById('status');let currentUtterance=null;
chapters.forEach((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=c.title;select.appendChild(o)});
function renderChapter(i){speechSynthesis.cancel();const c=chapters[i];readerTitle.textContent=c.title;readerKicker.textContent=c.kicker;readerText.textContent=c.text;status.textContent='Ready to listen.';localStorage.setItem('btcChapter',i)}
function loadVoices(){const voices=speechSynthesis.getVoices();voiceSelect.innerHTML='';voices.forEach((v,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${v.name} — ${v.lang}`;voiceSelect.appendChild(o)});const preferred=voices.findIndex(v=>/en-US/i.test(v.lang)&&/natural|samantha|ava|daniel|google/i.test(v.name));if(preferred>=0)voiceSelect.value=preferred}
loadVoices();speechSynthesis.onvoiceschanged=loadVoices;
select.addEventListener('change',e=>renderChapter(+e.target.value));rate.addEventListener('input',()=>rateLabel.textContent=`${rate.value}×`);
document.getElementById('playBtn').onclick=()=>{speechSynthesis.cancel();const c=chapters[+select.value];const u=new SpeechSynthesisUtterance(c.text);const voices=speechSynthesis.getVoices();if(voices[+voiceSelect.value])u.voice=voices[+voiceSelect.value];u.rate=+rate.value;u.pitch=1;u.onstart=()=>status.textContent=`Playing: ${c.title}`;u.onend=()=>status.textContent='Chapter finished.';u.onerror=()=>status.textContent='Audio playback stopped or is not supported by this browser.';currentUtterance=u;speechSynthesis.speak(u)};
document.getElementById('pauseBtn').onclick=()=>{if(speechSynthesis.speaking){speechSynthesis.pause();status.textContent='Paused.'}};
document.getElementById('resumeBtn').onclick=()=>{speechSynthesis.resume();status.textContent='Playing.'};
document.getElementById('stopBtn').onclick=()=>{speechSynthesis.cancel();status.textContent='Stopped.'};
const saved=+(localStorage.getItem('btcChapter')||0);select.value=saved;renderChapter(saved);