(function(){
  const RESTORE_KEY='fawFullMasterRestoreV1';
  if(typeof db==='undefined'||typeof enrich!=='function'||!db.campaigns)return;
  if(!db.campaigns[2026]) db.campaigns[2026]=newCampaign(2026,null);
  const c=db.campaigns[2026];

  const legacy=[
    {id:'rh',org:'RH Community Builders',worker:'Terrance',owner:'Terrance',contact:'Katie Wilbur / Brittany Hall',status:'Confirmed',value:1000,valueType:'Cash',address:'RH Community Builders, Fresno, CA',last:'Confirmed $1,000 sponsorship; sponsor benefits acknowledged.',next:'Collect/confirm qualifying logo and materials before Sept. 18.',notes:'Confirmed cash sponsorship.'},
    {id:'oakmont',org:'Oakmont Senior Living of Fresno',worker:'Terrance',owner:'Terrance',status:'Confirmed',value:250,valueType:'Cash',address:'Oakmont of Fresno, Fresno, CA',last:'Confirmed sponsor at the $250 level. Response already sent.',next:'Obtain/confirm Oakmont logo and add it to the FAW website.',notes:'No reply needed. Logo is needed/being added to the Fresno AIDS Walk website.'},
    {id:'amp',org:'Ampersand Ice Cream',worker:'Terrance',owner:'Terrance',contact:'Valerie Keffel, Director of Operations',status:'Confirmed',value:50,valueType:'In-kind',address:'1940 N Echo Ave, Fresno, CA',last:'Confirmed two $25 gift cards ($50 total).',next:'Pick up the two gift cards in October at 1940 N Echo.',notes:'Confirmed in-kind support.'},
    {id:'trader',org:"Trader Joe's Fresno",worker:'Terrance / call team',owner:'Brisa Mendoza',contact:'Store manager / Tony',phone:'559-433-6478',status:'Confirmed',value:40,valueType:'In-kind',method:'In person',address:'8478 N Friant Rd, Fresno, CA 93720',last:'Manager received the sponsorship packet and agreed to provide a $40 gift card in October 2026.',next:'Pick up/coordinate the $40 gift card in October and record receipt.',notes:'Confirmed in-kind support.'},
    {id:'lab',org:'La Boulangerie',worker:'Emily / call team',owner:'Delanie Sanchez',contact:'Harpreet',phone:'559-304-4967',status:'Confirmed',sector:'Food / Bakery',strength:'Established',probability:100,valueType:'In-kind',address:'730 W Shaw Ave, Fresno, CA 93704',ask:'Ask to renew the cake donation or increase in-kind support for the event.',last:'Cake donation confirmed for 2026.',next:'Coordinate donation closer to the event.',notes:'Returning supporter. Legacy route: returning in-kind donor.'},
    {id:'beneficial',org:'Beneficial State Bank',worker:'Terrance',owner:'Terrance',status:'Submitted',method:'Online application',address:'Beneficial State Bank, Fresno, CA',last:'Sponsorship application submitted Aug. 30, 2026.',next:'Await response and record decision or follow-up request.',notes:'Submitted / awaiting response.'},
    {id:'gwl',org:'Great Wolf Lodge — Southern California',worker:'Terrance',owner:'Andrea Gonzalez',status:'Submitted',method:'Online application',address:'Great Wolf Lodge Southern California, Garden Grove, CA',last:'Donation request submitted Aug. 25, 2026; auto-acknowledgement received.',next:'Track review outcome.',notes:'Review may take up to 30 days.'},
    {id:'ppm',org:'Planned Parenthood Mar Monte',worker:'Terrance',owner:'Terrance',contact:'Education Services team',email:'edservices@ppmarmonte.org',status:'Active',address:'Planned Parenthood Mar Monte, Fresno, CA',last:'Program Interest Form tracked as submitted Aug. 18. On Aug. 31, Education Services said they would like someone to attend and represent PPMM and asked whether the form was completed.',next:'Confirm the Program Interest Form was submitted and coordinate event representation/logistics.',notes:'Active follow-up; not yet counted as confirmed monetary sponsorship.'},
    {id:'cvs',org:'CVS Specialty / CVS Health',worker:'Terrance',owner:'Terrance',contact:'Drexel Shaw, MPH',contactRole:'Senior Manager, National Patient Advocacy and External Affairs',phone:'445-227-4240',status:'Waiting',address:'CVS, Fresno, CA',last:'Sponsorship remains under internal compliance and approval review; Drexel Shaw will follow up after a final decision.',next:'Do not over-contact; courteous follow-up only if no decision arrives after the review window.',notes:'Latest status from the Aug. 31 user-provided CVS email.'},
    {id:'tinder',org:'Tinder',worker:'Terrance',owner:'Terrance',contact:'Partnerships',email:'partners@gotinder.com',status:'Waiting',sector:'Technology / Dating',strength:'New',probability:25,method:'Email',address:'Tinder, Los Angeles, CA',ask:'Request event sponsorship or partnership aligned with LGBTQ+ community visibility and HIV awareness.',last:'Sponsorship email sent Aug. 18, 2026.',next:'Await response / follow up if appropriate.'},
    {id:'gilead',org:'Gilead',worker:'Ashley',owner:'Ashley Morris',status:'Waiting',address:'Gilead Sciences, Foster City, CA',last:'Ashley reached out Aug. 20 and LOI was sent.',next:'Await response and document decision.'},
    {id:'healthmerch',org:'HealthMerch',worker:'Terrance / Brisa',owner:'Terrance',contact:'Benjamin Sherman / Ashley',status:'Active',sector:'Merchandise / Event Production',strength:'Warm',probability:60,valueType:'In-kind',address:'HealthMerch, Fresno, CA',ask:'Ask for the strongest event-shirt discount or in-kind production contribution and document the dollar value saved.',last:'Positive response; discounted shirt production discussed as in-kind support.',next:'Finalize quote and document in-kind value.'},
    {id:'kaiser',org:'Kaiser Permanente — Fresno Area',worker:'Ashley',owner:'Ashley Morris',contact:'Samantha Schuh',status:'Submitted',sector:'Healthcare',method:'Online application',address:'Kaiser Permanente Fresno Medical Center, Fresno, CA',last:'Application link/user guide received; Ashley is handling the online application.',next:'Track decision when received.',notes:'Handled by Ashley.'},
    {id:'inlove',org:'#inLove',worker:'Emily / call team',owner:'Mark Campbell',contact:'Jorge Gaona',phone:'559-579-9260',status:'Needs Follow-Up',sector:'Local Business',strength:'Established',probability:45,address:'2767 W Shaw Ave, Fresno, CA 93705',ask:'Ask to renew or increase prior in-kind support.',last:'Voicemail left Aug. 18.',next:'Follow up and ask to renew/increase support.'},
    {id:'glacier',org:'Glacier Refrigeration & Air, Inc.',worker:'Emily / call team',owner:'Mark Campbell',contact:'Yvette',email:'Yvette@glacierref.com',phone:'559-891-0549',status:'Needs Follow-Up',sector:'HVAC / Local Business',strength:'Established',probability:45,address:'1200 Valley View, Selma, CA',ask:'Ask to renew sponsorship and consider increasing support.',last:'Voicemail left Aug. 18.',next:'Verify packet and follow up.'},
    {id:'larger',org:'Larger Electric',worker:'Call team',owner:'',status:'Needs Follow-Up',sector:'Electrical / Local Business',strength:'Warm',probability:30,address:'Larger Electric, Fresno, CA',ask:'Request local business sponsorship or in-kind support.',last:'Voicemail left Aug. 18.',next:'Follow up on voicemail.'},
    {id:'endowment',org:'The California Endowment',worker:'Call team',owner:'',status:'Needs Follow-Up',sector:'Philanthropy / Foundation',strength:'Warm',probability:30,address:'The California Endowment, Fresno, CA',ask:'Explore sponsorship or community-health support aligned with HIV prevention and health equity.',last:'Voicemail left Aug. 18.',next:'Follow up on voicemail.'},
    {id:'viiv',org:'ViiV Healthcare',worker:'Terrance / committee',owner:'Terrance',status:'Needs Follow-Up',sector:'Biopharma / HIV',strength:'Warm',probability:65,address:'The Living Room, Fresno, CA',ask:'Request HIV-focused sponsorship aligned with prevention, treatment access and community impact.',last:'Meeting scheduled Aug. 25 at The Living Room.',next:'Enter meeting outcome and sponsorship status.',notes:'Legacy status was Update Needed.'},
    {id:'willow',org:'Willow Gardens',worker:'Call team',owner:'',status:'Declined',sector:'Senior Living / Local Business',strength:'Warm',probability:0,address:'Willow Gardens, Fresno, CA',last:'Declined Aug. 18, 2026.',next:'No 2026 follow-up unless requested.',outcome:'Declined in 2026.'},
    {id:'tower',org:'Tower Theatre',worker:'Ricky / Terrance',owner:'Devin Sandoval',phone:'559-485-9050',email:'info@fresnotowertheatre.com',status:'Fix Contact',sector:'Arts / Entertainment',strength:'Warm',probability:30,address:'Tower Theatre, Fresno, CA',ask:'Request local arts/community sponsorship, tickets, promotional support or an in-kind contribution.',last:'Follow-up email bounced.',next:'Find a verified contact and resend packet.',notes:'Do not count bounced email as successful contact.'},
    {id:'nbc',org:'Nothing Bundt Cakes Fresno/Clovis',worker:'Emily / Terrance',owner:'Terrance',status:'Fix Contact',sector:'Food / Bakery',strength:'Warm',probability:40,address:'Nothing Bundt Cakes, Fresno, CA',ask:'Request cake/product donation, gift cards or sponsorship for the event.',last:'Prospect requested flyer; later follow-up email bounced.',next:'Find verified contact and resend flyer/packet.',notes:'Warm lead generated by Emily.'},
    {id:'clarice',org:'Clarice Arcia / Blade Works',worker:'Emily',owner:'Emily',contact:'Clarice Arcia',status:'Active',sector:'Beauty / Local Business',strength:'Warm',probability:45,address:'Blade Works, Fresno, CA',ask:'Confirm the organization and ask what type/value of donation they can provide.',last:'Donation interest reported.',next:'Confirm organization, donation type/value and pickup/delivery.',notes:'Legacy status: Warm Lead.'},
    {id:'lawrence',org:'Lawrence Engineering Group',worker:'Emily / Terrance',owner:'Terrance',status:'Waiting',sector:'Engineering / Local Business',strength:'Warm',probability:35,address:'Lawrence Engineering Group, Fresno, CA',ask:'Ask for cash sponsorship and highlight local community recognition.',last:'Follow-up / response pending.',next:'Continue follow-up and document response.'},
    {id:'moon',org:'Moon Salon Studios',worker:'Ricky / Terrance',owner:'Ashley Morris',phone:'559-455-3968',email:'moonsalonstudiosLLC@gmail.com',status:'Needs Follow-Up',sector:'Beauty / Local Business',strength:'New',probability:30,address:'405 E Olive Ave, Fresno, CA 93728',ask:'Request local business sponsorship, raffle item or service gift certificate.',last:'Follow-up outreach documented.',next:'Verify successful contact and follow up.'},
    {id:'centro',org:'Centro La Familia Advocacy Services',worker:'Terrance',owner:'Terrance',status:'Active',sector:'Community Services',strength:'Warm',probability:40,address:'302 Fresno St, Fresno, CA',ask:'Invite community partnership, sponsorship, tabling or in-kind support and connect the event to local families and health equity.',last:'Email sent Aug. 26.',next:'Monitor response; drop off packet if useful.'},
    {id:'big5',org:'Big 5 Sporting Goods',worker:'Terrance',owner:'Terrance',status:'Research Needed',sector:'Sporting Goods / Retail',strength:'New',probability:25,address:'Big 5 Sporting Goods, Fresno, CA',last:'Online donation route identified.',next:'Use the verified official route and log submission/reference number.',notes:'Legacy tracker estimated a 4–6 week process.'},
    {id:'aldi',org:'ALDI',worker:'Terrance',owner:'Terrance',status:'Research Needed',sector:'Grocery / Retail',strength:'New',probability:20,address:'ALDI, Fresno, CA',ask:'Use the community gift-card route only if the request fits program eligibility.',last:'Gift-card route identified.',next:'Verify current eligibility and submit only if appropriate.',notes:'Not a general event sponsorship route. Legacy status: Conditional.'},
    {id:'boa',org:'Bank of America',worker:'Terrance',owner:'Terrance',status:'Research Needed',sector:'Banking',strength:'New',probability:10,address:'Bank of America, Fresno, CA',last:'Application/grant route identified.',next:'Recheck the next official foundation cycle and eligibility.'},
    {id:'avita',org:'Avita Pharmacy',worker:'Terrance',owner:'Terrance',contact:'Rigoberto Martinez',status:'Active',sector:'Healthcare / Pharmacy',strength:'Warm',probability:50,address:'Avita Pharmacy, Fresno, CA',ask:'Request HIV-focused sponsorship and pharmacy/community-health partnership support.',last:'Named sponsorship contact identified.',next:'Contact and document result.',notes:'Legacy status: Direct Contact.'},
    {id:'bluemoon',org:'Blue Moon Yoga & Wellness',worker:'Emily',owner:'Emily',status:'Needs Follow-Up',sector:'Wellness / Fitness',strength:'Established',probability:55,address:'Blue Moon Yoga, Fresno, CA',ask:'Ask to renew 2026 in-kind support and consider increasing the contribution.',last:'Previous 2025 in-kind donor.',next:'Ask to renew 2026 support.',notes:'Legacy status: Renewal.'},
    {id:'tacos',org:'Tacos Marquitos',worker:'Emily / call team',owner:'Ashley Morris',contact:'Javier Rangel / Jesus Ibarra',phone:'559-477-5569',status:'Completed Contact',sector:'Food / Restaurant',strength:'Established',probability:50,address:'1772 E Barstow Ave, Fresno, CA 93710',ask:'Confirm 2026 commitment/value and event logistics.',last:'Contact marked completed.',next:'Confirm 2026 commitment/value and event logistics.'},
    {id:'hedricks',org:"Hedrick's Chevrolet",worker:'Emily / call team',owner:'Elisha Simpson Sanchez',contact:'Brett Hendricks',phone:'559-512-6549',status:'Needs Follow-Up',sector:'Automotive',strength:'Established',probability:50,address:"Hedrick's Chevrolet, Fresno, CA",ask:'Ask to renew or increase the prior cash sponsorship.',last:'Voicemail left; prior support documented.',next:'Follow up and ask to renew/increase sponsorship.'},
    {id:'roadsters',org:'Modesto Roadsters',worker:'Terrance',owner:'Terrance',status:'Submitted',sector:'Automotive / Club',strength:'New',probability:30,method:'Online application',address:'Modesto Roadsters, Modesto, CA',last:'Donation request submitted Aug. 26.',next:'Record approval/denial when received.'},
    {id:'nogos',org:'Nogos Hair Design',worker:'Ricky',owner:'Mark Campbell',contact:'Nogodar Martinez',phone:'559-907-2995',status:'Research Needed',sector:'Beauty / Local Business',strength:'New',probability:25,address:'Nogos Hair Design, Fresno, CA',ask:'Call and request first-time sponsorship or an in-kind donation.',last:'Listed for first-time sponsor outreach.',next:'Call and document result.'},
    {id:'imperio',org:'Imperio Del Glamour LLC',worker:'Ricky',owner:'Ruben Cueva',contact:'Roy Lara',phone:'559-360-4427',status:'Research Needed',sector:'Beauty / Local Business',strength:'New',probability:25,address:'2002 N Fine Ave Ste 101, Fresno, CA 93727',ask:'Call and request first-time sponsorship or an in-kind donation.',last:'Listed for first-time sponsor outreach.',next:'Call and document result.'},
    {id:'powerade',org:'Powerade',worker:'Ricky / research',owner:'Andrea Gonzalez',status:'Research Needed',sector:'Beverage / Consumer Brand',strength:'New',probability:20,address:'Powerade, Fresno, CA',ask:'Find the current sponsorship/community partnership route and request product or event support.',last:'Listed in research backlog.',next:'Find sponsorship contact.'},
    {id:'lions',org:'Central Valley Lions Club',worker:'Emily / research',owner:'Anthony Damian',contact:'Anthony Damian',status:'Research Needed',sector:'Service Club',strength:'Established',probability:60,address:'PO Box 1405, Selma, CA 93662',ask:'Ask to renew or increase prior $250 support.',last:'Prior support includes 2024 and 2025 $250 sponsorships.',next:'Find current contact and ask to renew/increase.',notes:'High-priority returning supporter.'},
    {id:'laestrella',org:'La Estrella',worker:'Ricky / research',owner:'Arturo Ramos',status:'Research Needed',sector:'Local Business',strength:'New',probability:20,address:'La Estrella, Fresno, CA',ask:'Find the current decision-maker and request sponsorship or in-kind support.',last:'Listed in research backlog.',next:'Find sponsorship contact.'},
    {id:'natalias',org:"Natalia's",worker:'Ricky / research',owner:'Arturo Ramos',status:'Research Needed',sector:'Local Business',strength:'New',probability:20,address:"Natalia's, Fresno, CA",ask:'Find the current decision-maker and request sponsorship or in-kind support.',last:'Listed in research backlog.',next:'Find sponsorship contact.'},
    {id:'rei',org:'REI',worker:'Ricky / research',owner:'Arturo Zuno',status:'Research Needed',sector:'Outdoor Retail',strength:'New',probability:20,address:'REI, Fresno, CA',last:'Listed in research backlog.',next:'Use verified public sponsorship/giving route.'},
    {id:'sunmaid',org:'Sun-Maid',worker:'Ricky / research',owner:'Arturo Zuno',status:'Research Needed',sector:'Food / Agriculture',strength:'New',probability:25,address:'Sun-Maid, Kingsburg, CA',last:'Listed in research backlog.',next:'Use verified Corporate Affairs contact route.'},
    {id:'apple',org:'Apple Inc.',worker:'Ricky / research',owner:'Ashley Morris',status:'Research Needed',sector:'Technology',strength:'New',probability:15,address:'Apple, Fresno, CA',ask:'Find the correct corporate/community giving route before outreach.',last:'Listed in research backlog.',next:'Find correct corporate/community giving route.'},
    {id:'dbh',org:'Fresno County Department of Behavioral Health',worker:'Ricky / research',owner:'Ashley Morris',status:'Research Needed',sector:'Government / Behavioral Health',strength:'New',probability:10,address:'Fresno County Department of Behavioral Health, Fresno, CA',last:'Listed in research backlog.',next:'Use verified department contact and ask whether partnership/promotion is permissible.'},
    {id:'eoc',org:'Fresno EOC',worker:'Emily / research',owner:'Ashley Morris',status:'Research Needed',sector:'Community Action',strength:'Established',probability:10,address:'Fresno EOC, Fresno, CA',ask:'When the route reopens, ask to renew or increase prior support.',last:'Prior support includes 2024 $1,000.',next:'Recheck the official sponsorship page for reopening.',notes:'High-priority prior supporter.'},
    {id:'genoa',org:'Genoa Healthcare',worker:'Ricky / research',owner:'Ashley Morris',status:'Research Needed',sector:'Healthcare / Pharmacy',strength:'New',probability:25,address:'Genoa Healthcare, Fresno, CA',last:'Listed in research backlog.',next:'Use verified marketing route and request appropriate sponsorship/community-giving contact.'},
    {id:'iheartradio',org:'iHeartMedia Fresno',worker:'Ricky / research',owner:'Ashley Morris',status:'Research Needed',sector:'Media',strength:'New',probability:25,address:'iHeartMedia Fresno, Fresno, CA',ask:'Ask for an in-kind media partnership: PSA spots, digital promotion, interviews or event mentions.',last:'Listed as media partner opportunity.',next:'Use verified Fresno advertising/community route.'}
  ];

  const timeline=[
    {id:'restore-kickoff',date:'2026-07-01',type:'Meeting',title:'Committee kick-off',owner:'Committee',notes:'2026 Fresno AIDS Walk confirmed for Nov. 7 at Woodward Park North East 12 Acres.'},
    {id:'restore-roles',date:'2026-08-10',type:'Meeting',title:'Sponsorship roles confirmed',owner:'Committee',notes:'Emily assigned returning sponsors, Ricky assigned new prospects, and Terrance handles mass email/tracking and applications.'},
    {id:'restore-amp',date:'2026-08-11',type:'Response',title:'Ampersand confirmed',owner:'Terrance',notes:'Two $25 gift cards confirmed for October pickup.'},
    {id:'restore-rh',date:'2026-08-12',type:'Response',title:'RH Community Builders confirmed',owner:'Terrance',notes:'$1,000 sponsorship documented.'},
    {id:'restore-major',date:'2026-08-18',type:'Outreach',title:'Major follow-up day',owner:'Committee',notes:'Planned Parenthood form submitted; Tinder email sent; several voicemail follow-ups and contact fixes documented.'},
    {id:'restore-cvs21',date:'2026-08-21',type:'Response',title:'CVS Specialty reviewing',owner:'Terrance',notes:'CVS Specialty expressed interest and began internal sponsorship review.'},
    {id:'restore-gwl',date:'2026-08-25',type:'Outreach',title:'Great Wolf submitted',owner:'Terrance',notes:'ApproveForGood donation request submitted.'},
    {id:'restore-aug26',date:'2026-08-26',type:'Outreach',title:'Additional outreach',owner:'Terrance',notes:'Centro La Familia email and Modesto Roadsters donation request documented.'},
    {id:'restore-aug30',date:'2026-08-30',type:'Response',title:'Trader Joe’s + Beneficial State Bank',owner:'Terrance',notes:'Trader Joe’s manager agreed to a $40 gift card in October. Beneficial State Bank sponsorship application submitted.'},
    {id:'restore-aug31',date:'2026-08-31',type:'Response',title:'Oakmont + PPMM + CVS updates',owner:'Terrance',notes:'Oakmont confirmed $250; PPMM followed up about attendance/representation; CVS remains under internal compliance and approval review.'}
  ];

  const map=new Map((c.sponsors||[]).map(x=>[x.id,enrich(x)]));
  function fillMissing(existing,source){
    const out={...existing};
    Object.keys(source).forEach(k=>{
      const v=out[k];
      if(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length)) out[k]=source[k];
    });
    if(source.worker&&!out.worker)out.worker=source.worker;
    return enrich(out);
  }
  legacy.forEach(r=>{
    const old=map.get(r.id);
    map.set(r.id,old?fillMissing(old,r):enrich(r));
  });
  c.sponsors=[...map.values()].filter(x=>x.id!=='downing');
  c.calendar=c.calendar||[];
  const calIds=new Set(c.calendar.map(x=>x.id));
  timeline.forEach(x=>{if(!calIds.has(x.id))c.calendar.push(x)});
  c.activity=c.activity||[];
  if(!localStorage.getItem(RESTORE_KEY)){
    c.activity.unshift({at:new Date().toISOString(),summary:'Restored the full 2026 FAW master sponsor list and historical campaign timeline into the professional Sponsorship Intelligence app.',source:'Merged from the prior 2026 FAW master tracker; Downing Mountain Lodge remains intentionally excluded.'});
    localStorage.setItem(RESTORE_KEY,'1');
  }
  save();
  if(typeof renderAll==='function')renderAll();
})();